"""Add value column

Revision ID: 633c7f90905f
Revises: aab0b1166098
Create Date: 2023-02-09 16:15:12.027506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633c7f90905f'
down_revision = 'aab0b1166098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
