"""Added key column to address

Revision ID: a0841a26eff4
Revises: 3d6f3b7e9950
Create Date: 2023-02-09 15:29:44.781999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0841a26eff4'
down_revision = '3d6f3b7e9950'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_address', sa.Column('key', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_address', 'key')
    # ### end Alembic commands ###
