"""Add value column

Revision ID: aab0b1166098
Revises: a0841a26eff4
Create Date: 2023-02-09 16:05:20.170260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab0b1166098'
down_revision = 'a0841a26eff4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_address', sa.Column('value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_address', 'value')
    # ### end Alembic commands ###
